apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
    environment: dev
    managed-by: kubectl
---
apiVersion: v1
kind: Namespace
metadata:
  name: uat
  labels:
    name: uat
    environment: uat
    managed-by: kubectl
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod
    environment: prod
    managed-by: kubectl
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    managed-by: kubectl
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
    managed-by: kubectl
