apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  namespace: uat
data:
  ENV: "uat"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "agnos"
  WORKER_INTERVAL: "60"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring:4317"
