apiVersion: v1
kind: Service
metadata:
  name: worker
  labels:
    app: worker
spec:
  clusterIP: None
  selector:
    app: worker
  ports:
    - name: placeholder
      port: 80
      targetPort: 80
      protocol: TCP
